config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'

  get 'dashboard/show'
  resources :shouts, only: [:create, :show] do
    member do
      post 'like' => 'likes#create'
    end
  end
  root to: 'home#index'
  devise_for :users
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image_shout.rb
class ImageShout < ApplicationRecord
  has_attached_file :image, styles: { thumb: '200x200' }
  validates_attachment :image,
                       content_type: { content_type: %w[image/jpeg image/gif image/png] },
                       size: { in: 0..10.megabytes },
                       presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :shout

  validates :user_id, uniqueness: {  scope: :shout_id }
end

app/models/shout.rb
class Shout < ApplicationRecord
  belongs_to :user
  belongs_to :content, polymorphic: true
  default_scope { order(created_at: :desc) }
  delegate :username, to: :user
end

app/models/text_shout.rb
class TextShout < ApplicationRecord
  validates :body, length: { in: 1..150 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
  attr_accessor :login
  validates :username, presence: true, uniqueness: true
  has_many :shouts, dependent: :destroy
  has_many :likes
  has_many :liked_shouts, through: :likes, source: :shout
  def self.find_for_database_authentication warden_conditions
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
  end

  def like(shout)
    liked_shouts << shout
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    dashboard_show_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :current_password])
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @shout = Shout.new
    @shouts = current_user.shouts
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    current_user.like(shout)
    redirect_to root_path
  end
  
  private
  
  def shout
    @_shout || Shout.find(params[:id])
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  def show
    @shout = Shout.find(params[:id])
  end

  def create
    shout = current_user.shouts.create(shout_params)
    redirect_to dashboard_show_path, redirect_options_for(shout)
  end

  private

  def shout_params
    { content: content_from_params }
  end

  def content_from_params
    case params[:shout][:content_type]
    when 'TextShout' then TextShout.new(text_shout_content_params)
    else ImageShout.new(image_shout_content_params)
    end
  end

  def text_shout_content_params
    params.require(:shout).require(:content).permit(:body)
  end

  def image_shout_content_params
    params.require(:shout).require(:content).permit(:image)
  end

  def redirect_options_for(shout)
    if shout.persisted?
      { notice: "Shout created!" }
    else
      { alert: "Could not shout. Sorry" }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @shouts = @user.shouts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/shouts_helper.rb
module ShoutsHelper
  def avatar(user)
    email_digest = Digest::MD5.hexdigest user.email
    gravatar_url = "//www.gravatar.com/avatar/#{email_digest}"
    image_tag gravatar_url
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/show.html.haml
%p
  You are signed in as #{current_user.email}
  = link_to 'Sign Out', destroy_user_session_path(@user), method: :delete

%h1 Dashboard

= form_for @shout do |f|
  = f.hidden_field :content_type, value: 'TextShout'
  = f.fields_for :content do |cform|
    = cform.text_field :body, placeholder: "Shout here!", required: true
    = cform.submit "Shout!"

= form_for @shout do |f|
  = f.hidden_field :content_type, value: 'ImageShout'
  = f.fields_for :content do |cform|
    = cform.file_field :image, required: true
    = cform.submit "Shout!"

= render @shouts

app/views/home/index.html.haml
%h1 Home

- if user_signed_in?
  = link_to 'Sign Out', destroy_user_session_path(@user), method: :delete
- else
  = link_to 'Sign In', new_user_session_path
  or
  = link_to 'Sign Up', new_user_registration_path

app/views/image_shouts/_image_shout.html.haml
= image_tag(image_shout.image(:thumb))

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Shoutbox
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/likes/create.html.haml
%h1 Likes#create
%p Find me in app/views/likes/create.html.haml

app/views/shouts/_shout.html.haml
%div
  = avatar(shout.user)
  = link_to shout.username, shout.user
  = render shout.content
  = link_to shout do
    = time_ago_in_words(shout.created_at)
    ago
  = link_to 'Like', like_shout_path(shout), method: :post

app/views/shouts/create.html.haml
%h1 Shouts#create
%p Find me in app/views/shouts/create.html.haml

app/views/shouts/show.html.haml
= render @shout

app/views/text_shouts/_text_shout.html.haml
= text_shout.body

app/views/users/show.html.haml
%h1= @user.username

= render @shouts